# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'B. Quint'
tagline:          'A sample page for my home page. :p'
description:      'Just a dummy page'
url:              'https://b1quint.github.io/'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Bruno Corrêa Quint'

  name   : "Your Name"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  url:              'https://b1quint.github.io/'

  #Social Media links (Use complete URL except for email)
  dribbble:
  email:
  facebook:       ''
  flickr:
  github:         ''
  gplus:          ''
  instagram:
  pinterest:
  linkedin:       ''
  rss:
  stackoverflow:  ''
  twitter:        ''

# Google Analytics
gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2

# Adding the repository name
repository: "b1quint/b1quint.github.io"

# Setting the teaser image
teaser: /assets/images/500x300.png

# Enable breadcrumb links
breadcrumbs: true  # disabled by default

# Enable readtime
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

# Disable comments
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: false

# Including new folders with pages
include: ["_pages"]
